### PR TITLE
  Fix Objective-C nullability compilation errors in iOS SDK 6.10.1

### PR DESCRIPTION
**Pull request by sergiothinks2**
Problem: Compilation errors when upgrading from EmbraceIO 6.9.2 to 6.10.1 due to missing nullability type specifiers in Objective-C code.

  Root Cause: C function declarations require explicit nullability annotations even within NS_ASSUME_NONNULL_BEGIN/END blocks, and some properties needed explicit nullability annotations.

  Changes:
  - Added explicit _Nonnull/_Nullable annotations to all C function parameters in EMBURLSessionDelegateProxyFunctions.h (20 functions)
  - Fixed nullability annotations for block parameters and weak properties in EMBStartupTracker.h
  - Fixed typo in UIKit import (Uikit.h → UIKit.h) in EMBDisplayLinkProxy.m

  Impact: Resolves "Pointer is missing a nullability type specifier" compilation errors for customers using strict nullability checking in Xcode.

### CODE REVIEW

File: Sources/EmbraceObjCUtilsInternal/include/EMBStartupTracker.h [hunk 1]
```diff
@@ -13,17 +13,17 @@ NS_ASSUME_NONNULL_BEGIN
 @property (nonatomic, strong) NSDate *constructorClosestToMainTime;
 
 @property (nonatomic, strong, nullable) NSDate *firstFrameTime;
-@property (nonatomic, copy, nullable) void (^onFirstFrameTimeSet)(NSDate *);
+@property (nonatomic, copy, nullable) void (^onFirstFrameTimeSet)(NSDate * _Nonnull);
```
Comment (naftaly) [inline Sources/EmbraceObjCUtilsInternal/include/EMBStartupTracker.h:16]: surprising that block parameters need explicit nullability annotations.

File: Sources/EmbraceObjCUtilsInternal/source/EMBDisplayLinkProxy.m [hunk 2]
```diff
@@ -2,7 +2,7 @@
 //  Copyright © 2025 Embrace Mobile, Inc. All rights reserved.
 //
 
-#import <UIKit/Uikit.h>
+#import <UIKit/UIKit.h>
```
Comment (naftaly) [inline Sources/EmbraceObjCUtilsInternal/source/EMBDisplayLinkProxy.m:5]: 🫠

File: Sources/EmbraceObjCUtilsInternal/include/EMBURLSessionDelegateProxyFunctions.h
Comment (naftaly) [inline Sources/EmbraceObjCUtilsInternal/include/EMBURLSessionDelegateProxyFunctions.h:1]: The changes required here shouldn't be needed. Can you share the errors you're seeing? Is it in a specific project, or just by running tests?
